### ISSUE TITLE
I have collected the dataset to pl_train.py for training but the training error

### ISSUE THREAD

**Issue by yihsinma** [qintonguav/e2e-parking-carla#21]
@qintonguav 
My environment : Ubuntu20.04 cuda11.7 python3.7 
I use train : 8 dataset val : 2 dataset
python pl_train.py error 
Please tell me how to solve this error
thx.
(E2EParking) lab328@lab328:~/e2e-parking-carla$ python pl_train.py  
Global seed set to 42
2024-09-30 16:52:46.599 | INFO     | __main__:train:36 - Config Yaml File: ./config/training.yaml
Trainer already configured with model summary callbacks: [<class 'pytorch_lightning.callbacks.model_summary.ModelSummary'>]. Skipping setting a default `Mod
elSummary` callback.
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
Loaded pretrained weights for efficientnet-b4
/home/lab328/anaconda3/envs/E2EParking/lib/python3.7/site-packages/torchvision/models/_utils.py:209: UserWarning: The parameter 'pretrained' is deprecated s
ince 0.13 and may be removed in the future, please use 'weights' instead.
 f"The parameter '{pretrained_param}' is deprecated since 0.13 and may be removed in the future, "
/home/lab328/anaconda3/envs/E2EParking/lib/python3.7/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `Non
e` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
 warnings.warn(msg)
2024-09-30 16:52:55.818 | INFO     | dataset.carla_dataset:get_data:374 - Preloaded 47611 sequences
2024-09-30 16:52:58.020 | INFO     | dataset.carla_dataset:get_data:374 - Preloaded 12602 sequences
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Missing logger folder: ./log/exp_2024_9_30_16_52_46/default

  | Name                            | Type             | Params
----------------------------------------------------------------------
0  | control_loss_func               | ControlLoss      | 0      
1  | control_loss_func.ce_loss       | CrossEntropyLoss | 0      
2  | control_val_loss_func           | ControlValLoss   | 0      
3  | control_val_loss_func.ce_loss   | CrossEntropyLoss | 0      
4  | control_val_loss_func.l1_loss   | SmoothL1Loss     | 0      
5  | segmentation_loss_func          | SegmentationLoss | 0      
6  | depth_loss_func                 | DepthLoss        | 0      
7  | parking_model                   | ParkingModel     | 28.1 M
8  | parking_model.bev_model         | BevModel         | 4.8 M  
9  | parking_model.bev_encoder       | BevEncoder       | 11.4 M
10 | parking_model.feature_fusion    | FeatureFusion    | 5.4 M  
11 | parking_model.control_predict   | ControlPredict   | 6.5 M  
12 | parking_model.segmentation_head | SegmentationHead | 66.2 K
----------------------------------------------------------------------
28.0 M    Trainable params
147 K     Non-trainable params
28.1 M    Total params
112.539   Total estimated model params size (MB)
Global seed set to 42                                                                                                                                                 
Epoch 1:   0%|                                                                                                           | 0/5951 [00:00<?, ?it/s, loss=8.7, v_num=0]
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7ff79d2bf050>
Traceback (most recent call last):
 File "/home/lab328/anaconda3/envs/E2EParking/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1466, in __del__
   self._shutdown_workers()
 File "/home/lab328/anaconda3/envs/E2EParking/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1449, in _shutdown_workers
   if w.is_alive():
 File "/home/lab328/anaconda3/envs/E2EParking/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
   assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7ff79d2bf050>
Traceback (most recent call last):
 File "/home/lab328/anaconda3/envs/E2EParking/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1466, in __del__
   self._shutdown_workers()
 File "/home/lab328/anaconda3/envs/E2EParking/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1449, in _shutdown_workers
   if w.is_alive():
 File "/home/lab328/anaconda3/envs/E2EParking/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7ff79d2bf050>
Traceback (most recent call last):
 File "/home/lab328/anaconda3/envs/E2EParking/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1466, in __del__
   assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
   self._shutdown_workers()
 File "/home/lab328/anaconda3/envs/E2EParking/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1449, in _shutdown_workers
   if w.is_alive():
 File "/home/lab328/anaconda3/envs/E2EParking/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
   assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7ff79d2bf050>
Traceback (most recent call last):
 File "/home/lab328/anaconda3/envs/E2EParking/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1466, in __del__
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7ff79d2bf050>
Traceback (most recent call last):
 File "/home/lab328/anaconda3/envs/E2EParking/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1466, in __del__
   self._shutdown_workers()
 File "/home/lab328/anaconda3/envs/E2EParking/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1449, in _shutdown_workers
   self._shutdown_workers()
 File "/home/lab328/anaconda3/envs/E2EParking/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1449, in _shutdown_workers
   if w.is_alive():
 File "/home/lab328/anaconda3/envs/E2EParking/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
   assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
   if w.is_alive():
 File "/home/lab328/anaconda3/envs/E2EParking/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
   assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7ff79d2bf050>
Traceback (most recent call last):
 File "/home/lab328/anaconda3/envs/E2EParking/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1466, in __del__
   self._shutdown_workers()
 File "/home/lab328/anaconda3/envs/E2EParking/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1449, in _shutdown_workers
   if w.is_alive():
 File "/home/lab328/anaconda3/envs/E2EParking/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
   assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7ff79d2bf050>
Traceback (most recent call last):
 File "/home/lab328/anaconda3/envs/E2EParking/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1466, in __del__
   self._shutdown_workers()
 File "/home/lab328/anaconda3/envs/E2EParking/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1449, in _shutdown_workers
   if w.is_alive():
 File "/home/lab328/anaconda3/envs/E2EParking/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
   assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7ff79d2bf050>
Traceback (most recent call last):
 File "/home/lab328/anaconda3/envs/E2EParking/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1466, in __del__
   self._shutdown_workers()
 File "/home/lab328/anaconda3/envs/E2EParking/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1449, in _shutdown_workers
   if w.is_alive():
 File "/home/lab328/anaconda3/envs/E2EParking/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
   assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process

**Comment by yihsinma** [comment]
@qintonguav please help me

**Comment by aapeng-s** [comment]
have you sloved this problem?
