### ISSUE TITLE
Log is not found when running the evaluation

### ISSUE THREAD

**Issue by jeremy7703** [qintonguav/e2e-parking-carla#24]
python3 carla_parking_eva.py
pygame 2.5.0 (SDL 2.28.0, Python 3.7.16)
Hello from the pygame community. https://www.pygame.org/contribute.html
INFO: listening to server 127.0.0.1:2000
INFO: Load Map Town04_Opt
INFO: ***************** Start init eva environment *****************
INFO: Init ego vehicle success!
INFO: Init sensors success!
INFO: Init weather success!
INFO: *****************   End init eva environment *****************
INFO: ***************** Start eva epoch 1 *****************
INFO: total parking points: 64
INFO: spawn 45 static vehicle in parking lot
INFO: set 25 parking goal
INFO: ***************** Start eva task 2-1 *****************
log/exp_2024_11_16_20_4_15
Traceback (most recent call last):
  File "carla_parking_eva.py", line 168, in <module>
    main()
  File "carla_parking_eva.py", line 161, in main
    game_loop(args)
  File "carla_parking_eva.py", line 24, in game_loop
    parking_agent = ParkingAgent(network_evaluator, args)
  File "/home/jeremy/e2e-parking-carla/agent/parking_agent.py", line 213, in __init__
    self.log_path.mkdir()
  File "/home/jeremy/anaconda3/envs/E2EParking/lib/python3.7/pathlib.py", line 1273, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'log/exp_2024_11_16_20_4_15'

**Comment by jeremy7703** [comment]
It seems like I need to manually created the log directory?
